package org.example.Enums;

public enum Type {
    LEAFY_GREENS,
    ROOT_VEGETABLES,
    CRUCIFEROUS_VEGETABLES,
    ALLIUM_VEGETABLES,
    NIGHTSHADE_VEGETABLES,
    GOURD_AND_SQUASH_VEGETABLES,
    PEPPERS,
    LEGUMES
}
